name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: 7.1
            symfony-version: 3.4.*
          - php-version: 7.4
            symfony-version: 3.4.*
          - php-version: 7.1
            symfony-version: 4.4.*
          - php-version: 7.4
            symfony-version: 4.4.*
          - php-version: 7.2
            symfony-version: 5.1.*
          - php-version: 7.4
            symfony-version: 5.1.*

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.0.0

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@2.4.2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: "Require dependencies"
        run: |
          composer require --no-update symfony/console:${{ matrix.symfony-version }} symfony/framework-bundle:${{ matrix.symfony-version }}

      - name: "Require symfony/messenger dependencies when possible"
        if: matrix.symfony-version != '3.4.*'
        run: |
          composer require --no-update symfony/messenger:${{ matrix.symfony-version }}

      - name: "Install dependencies with composer"
        run: |
          composer update --no-interaction --no-progress --no-suggest

      - name: "Run tests with phpunit/phpunit"
        run: vendor/bin/phpunit
